### ISSUE TITLE
Incomplete description in README's "How to add a new queue implementation"

### ISSUE THREAD

**Issue by jeehoonkang** [chaoran/hpc-queue#5]
Hi!  I'm porting the queue described in [1] to Rust: https://github.com/jeehoonkang/crossbeam-queue  It's a work in progress, but soon I'd like to evaluate its performance using the benchmark tools in this repo (mainly for comparing with the implementation in `wfqueue.c`).

So I'm following the instruction in README.md [2] for adding a new queue implementation, but I found that README.md differs from what is described in `queue.h`, esp.:

- It seems I need to implement `queue_free`, but it's not documented in the README.
- `EMPTY` is described in README, but it is not declared in `queue.h`.

I could kinda guess what are they, but I wonder if the author of this repository could clarify their meanings.  Thank you very much!

[1] Yang and Mellor-Crummey.  A Wait-free Queue as Fast as Fetch-and-Add.  PPoPP 2016.
[2]  https://github.com/chaoran/fast-wait-free-queue/blob/master/README.md#how-to-add-a-new-queue-implementation

**Comment by chaoran** [comment]
1. Yes, you need to implement `queue_free`. I will add it in the README.
2. EMPTY is an macro that you should define in your implementation header file. For example, wfqueue.h defines EMPTY.

**Comment by chaoran** [comment]
Please let me know if you have any questions. Rust is a very promising language. :) @jeehoonkang
